version: "3.4"
services:
  eth1:
    container_name: eth1-geth-net${ETH1_NETWORK_ID}
    restart: unless-stopped
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./
      dockerfile: Dockerfile.binary
      args:
        - USER=${GETH_USER}
        - UID=${LOCAL_UID}
        - DOCKER_TAG=${GETH_DOCKER_TAG}
    image: geth
    volumes:
      - geth-data:/var/lib/goethereum
    networks:
      - ethnet
    ports:
      - ${ETH1_PORT}:${ETH1_PORT}/tcp
      - ${ETH1_PORT}:${ETH1_PORT}/udp
    expose:
      - ${ETH1_RPC_PORT}/tcp
      - ${ETH1_WS_PORT}/tcp
    entrypoint:
      - geth
      - --nousb
      - --http
      - --http.addr=0.0.0.0
      - --http.vhosts=eth1,localhost
      - --http.api=eth,net
      - --datadir=/var/lib/goethereum
      - --port=${ETH1_PORT}
      - --http.port=${ETH1_RPC_PORT}
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=${ETH1_WS_PORT}
      - --ws.api=eth,net
      - --ws.origins='*'
      - --networkid=${ETH1_NETWORK_ID}
volumes:
  geth-data:
    name: eth1-geth-net${ETH1_NETWORK_ID}-data
networks:
  eth1net:
    name: eth1net
