version: "3.5"

services:  
  node-exporter:
    container_name: ${COMPOSE_PROJECT_NAME}-node
    restart: unless-stopped
    image: prom/node-exporter
    volumes:
      - '/:/host:ro,rslave'
    expose:
      - 9100/tcp
    networks:
      - grafananet
    command:
      - --path.rootfs=/host
  node-prometheus:
    container_name: ${COMPOSE_PROJECT_NAME}-prometheus
    restart: unless-stopped
    image: prom/prometheus
    volumes:
      - node-prometheus-data:/prometheus
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - 9090/tcp
    networks:
      - grafananet
    entrypoint:
      - /bin/prometheus
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - node-exporter

volumes:
  node-prometheus-data:
    name: ${COMPOSE_PROJECT_NAME}-prometheus-data