version: "3.5"

x-common: &common
  restart: unless-stopped
  user: ${LOCAL_UID}:${LOCAL_UID}
  build:
    context: ./
    dockerfile: Lighthouse.Dockerfile
    args:
      - USER=${LH_USER}
      - UID=${LOCAL_UID}
      - DOCKER_TAG=${LH_DOCKER_TAG}
  image: node/lighthouse

services:
  beacon:
    container_name: ${COMPOSE_PROJECT_NAME}-${CLIENT_NAME}-bn
    <<: *common
    volumes:
      - lighthouse-bn-data:/var/lib/lighthouse
    networks:
      - eth1net
      - eth2net
    ports:
      - ${LH_PORT}:${LH_PORT}/tcp
      - ${LH_PORT}:${LH_PORT}/udp
      - 127.0.0.1:${LH_HTTP_PORT}:${LH_HTTP_PORT}/tcp
    expose:
      - 5054/tcp
    entrypoint: 
      - lighthouse
      - bn
      - --datadir=/var/lib/lighthouse
      - --http
      - --http-address=0.0.0.0
      - --http-port=${LH_HTTP_PORT}
      - --http-allow-origin=*
      - --network=${ETH2_NETWORK}
      - --port=${LH_PORT}
      - --discovery-port=${LH_PORT}
      - --eth1-endpoints=${ETH1_NODE}
      - --debug-level=${LOG_LEVEL}
      - --metrics
      - --metrics-address=0.0.0.0      
  validator:
    container_name: ${COMPOSE_PROJECT_NAME}-${CLIENT_NAME}-vc
    <<: *common
    volumes:
      - lighthouse-vc-data:/var/lib/lighthouse
    networks:
      - eth2net
    expose:
      - 5064/tcp      
    entrypoint:
      - lighthouse
      - validator
      - --datadir=/var/lib/lighthouse
      - --beacon-node=${ETH2_NODE}
      - --graffiti=${GRAFFITI}
      - --network=${ETH2_NETWORK}
      - --debug-level=${LOG_LEVEL}
      - --metrics
      - --metrics-address=0.0.0.0

  eth2-prometheus:
    container_name: ${COMPOSE_PROJECT_NAME}-prometheus
    restart: unless-stopped
    image: prom/prometheus
    volumes:
      - lighthouse-prometheus-data:/prometheus
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - 9090/tcp
    networks:
      - eth2net
    entrypoint:
      - /bin/prometheus
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - beacon
      - validator

volumes:
  lighthouse-bn-data:
    name: ${COMPOSE_PROJECT_NAME}-${CLIENT_NAME}-bn-data
  lighthouse-vc-data:
    name: ${COMPOSE_PROJECT_NAME}-${CLIENT_NAME}-vc-data
  lighthouse-prometheus-data:
    name: ${COMPOSE_PROJECT_NAME}-${CLIENT_NAME}-prometheus-data

networks:
  eth2net:
    name: ${COMPOSE_PROJECT_NAME}-net
  eth1net:
    name: ${ETH1_PROJECT_NAME}-net
    external: true
  
