version: "3.4"
services:
  validator:
    container_name: eth2-lighthouse-vc-${NETWORK}
    restart: unless-stopped
    user: ${LOCAL_UID}:${LOCAL_UID}
    build:
      context: ./
      dockerfile: Dockerfile.binary
      args:
        - USER=${LH_USER}
        - UID=${LOCAL_UID}
        - DOCKER_TAG=${LH_DOCKER_TAG}
    image: lighthouse
    volumes:
      - lighthouse-vc-data:/var/lib/lighthouse
    entrypoint:
      - lighthouse
      - validator
      - --datadir=/var/lib/lighthouse
      - --beacon-node=http://beacon:5052
      - --graffiti=${GRAFFITI}
      - --network=${NETWORK}
      - --debug-level=${LOG_LEVEL}
volumes:
  lighthouse-vc-data: